run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - dupl #temporary
    - exhaustruct
    - gochecknoinits
    - forbidigo
    - gochecknoglobals
    - goimports
    # deprecated
    - exhaustivestruct
    - interfacer
    - maligned
    - scopelint
    - structcheck
    - varcheck
    - deadcode
    - ifshort
    - golint
    - nosnakecase
    - testpackage
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/mattn/go-isatty
          - github.com/muesli/mango-cobra
          - github.com/muesli/roff
          - github.com/nwidger/jsoncolor
          - github.com/oklog/ulid/v2
          - github.com/openfga/api
          - github.com/openfga/cli
          - github.com/openfga/go-sdk
          - github.com/openfga/language
          - github.com/openfga/openfga
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/spf13/viper
          - google.golang.org/protobuf/encoding/protojson
          - google.golang.org/protobuf/types/known/structpb
          - gopkg.in/yaml.v3
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/golang/mock/gomock
          - github.com/openfga/cli
          - github.com/openfga/go-sdk
          - github.com/openfga/openfga
          - github.com/stretchr

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

  funlen:
    lines: 120
    statements: 80

  skip-dirs:
    - mocks
